[agent]
  interval            = "60s"
  round_interval      = true
  metric_batch_size   = 1000
  metric_buffer_limit = 10000
  collection_jitter   = "5s"
  flush_interval      = "10s"
  flush_jitter        = "5s"
  precision           = ""
  hostname            = "nas-ex2ultra"
  omit_hostname       = false

[[outputs.influxdb]]
  urls             = ["http://127.0.0.1:8086"]
  database         = "sensor_data"
  skip_database_creation = true
  timeout          = "5s"

[[inputs.cpu]]
  percpu           = true
  totalcpu         = true
  collect_cpu_time = false
  report_active    = false

[[inputs.mem]]

[[inputs.swap]]

[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]

[[inputs.diskio]]

[[inputs.net]]
  interfaces = ["eth0", "bond0", "lo"]
  ignore_protocol_stats = true

[[inputs.system]]

[[inputs.processes]]

[[inputs.kernel]]
