profile|friendly_name|file_size|processor|filename|gpu_layers|ctx_size|threads
experi|llama3.3-8b|4.4G|gpu|llama3.3-8b.gguf|30|4096|8
fast|Phi-4-mini-Q6_K|3.0G|gpu|microsoft_Phi-4-mini-instruct-Q6_K.gguf|33|8192|8
think|Qwen3-8B-Q4_K_M|4.7G|gpu|Qwen_Qwen3-8B-Q4_K_M.gguf|28|4096|8
unallocated|Phi-4-mini-Q8_0|3.9G|gpu|microsoft_Phi-4-mini-instruct-Q8_0.gguf|33|4096|8
unallocated|Qwen3-8B-IQ3_M|3.7G|gpu|Qwen_Qwen3-8B-IQ3_M.gguf|33|4096|8
