# CMake generated Testfile for 
# Source directory: /home/wayne/llama.cpp/tests
# Build directory: /home/wayne/ubuntu-console/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[test-tokenizer-0-bert-bge]=] "/home/wayne/ubuntu-console/bin/test-tokenizer-0" "/home/wayne/llama.cpp/models/ggml-vocab-bert-bge.gguf")
set_tests_properties([=[test-tokenizer-0-bert-bge]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/wayne/llama.cpp/tests/CMakeLists.txt;40;add_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;122;llama_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-tokenizer-0-command-r]=] "/home/wayne/ubuntu-console/bin/test-tokenizer-0" "/home/wayne/llama.cpp/models/ggml-vocab-command-r.gguf")
set_tests_properties([=[test-tokenizer-0-command-r]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/wayne/llama.cpp/tests/CMakeLists.txt;40;add_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;123;llama_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-tokenizer-0-deepseek-coder]=] "/home/wayne/ubuntu-console/bin/test-tokenizer-0" "/home/wayne/llama.cpp/models/ggml-vocab-deepseek-coder.gguf")
set_tests_properties([=[test-tokenizer-0-deepseek-coder]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/wayne/llama.cpp/tests/CMakeLists.txt;40;add_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;124;llama_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-tokenizer-0-deepseek-llm]=] "/home/wayne/ubuntu-console/bin/test-tokenizer-0" "/home/wayne/llama.cpp/models/ggml-vocab-deepseek-llm.gguf")
set_tests_properties([=[test-tokenizer-0-deepseek-llm]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/wayne/llama.cpp/tests/CMakeLists.txt;40;add_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;125;llama_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-tokenizer-0-falcon]=] "/home/wayne/ubuntu-console/bin/test-tokenizer-0" "/home/wayne/llama.cpp/models/ggml-vocab-falcon.gguf")
set_tests_properties([=[test-tokenizer-0-falcon]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/wayne/llama.cpp/tests/CMakeLists.txt;40;add_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;126;llama_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-tokenizer-0-gpt-2]=] "/home/wayne/ubuntu-console/bin/test-tokenizer-0" "/home/wayne/llama.cpp/models/ggml-vocab-gpt-2.gguf")
set_tests_properties([=[test-tokenizer-0-gpt-2]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/wayne/llama.cpp/tests/CMakeLists.txt;40;add_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;127;llama_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-tokenizer-0-llama-bpe]=] "/home/wayne/ubuntu-console/bin/test-tokenizer-0" "/home/wayne/llama.cpp/models/ggml-vocab-llama-bpe.gguf")
set_tests_properties([=[test-tokenizer-0-llama-bpe]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/wayne/llama.cpp/tests/CMakeLists.txt;40;add_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;128;llama_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-tokenizer-0-llama-spm]=] "/home/wayne/ubuntu-console/bin/test-tokenizer-0" "/home/wayne/llama.cpp/models/ggml-vocab-llama-spm.gguf")
set_tests_properties([=[test-tokenizer-0-llama-spm]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/wayne/llama.cpp/tests/CMakeLists.txt;40;add_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;129;llama_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-tokenizer-0-mpt]=] "/home/wayne/ubuntu-console/bin/test-tokenizer-0" "/home/wayne/llama.cpp/models/ggml-vocab-mpt.gguf")
set_tests_properties([=[test-tokenizer-0-mpt]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/wayne/llama.cpp/tests/CMakeLists.txt;40;add_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;130;llama_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-tokenizer-0-phi-3]=] "/home/wayne/ubuntu-console/bin/test-tokenizer-0" "/home/wayne/llama.cpp/models/ggml-vocab-phi-3.gguf")
set_tests_properties([=[test-tokenizer-0-phi-3]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/wayne/llama.cpp/tests/CMakeLists.txt;40;add_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;131;llama_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-tokenizer-0-qwen2]=] "/home/wayne/ubuntu-console/bin/test-tokenizer-0" "/home/wayne/llama.cpp/models/ggml-vocab-qwen2.gguf")
set_tests_properties([=[test-tokenizer-0-qwen2]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/wayne/llama.cpp/tests/CMakeLists.txt;40;add_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;132;llama_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-tokenizer-0-refact]=] "/home/wayne/ubuntu-console/bin/test-tokenizer-0" "/home/wayne/llama.cpp/models/ggml-vocab-refact.gguf")
set_tests_properties([=[test-tokenizer-0-refact]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/wayne/llama.cpp/tests/CMakeLists.txt;40;add_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;133;llama_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-tokenizer-0-starcoder]=] "/home/wayne/ubuntu-console/bin/test-tokenizer-0" "/home/wayne/llama.cpp/models/ggml-vocab-starcoder.gguf")
set_tests_properties([=[test-tokenizer-0-starcoder]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/wayne/llama.cpp/tests/CMakeLists.txt;40;add_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;134;llama_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-tokenizers-ggml-vocabs]=] "/home/wayne/llama.cpp/tests/test-tokenizers-repo.sh" "https://huggingface.co/ggml-org/vocabs" "/home/wayne/llama.cpp/models/ggml-vocabs")
set_tests_properties([=[test-tokenizers-ggml-vocabs]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "/home/wayne/ubuntu-console/bin" _BACKTRACE_TRIPLES "/home/wayne/llama.cpp/tests/CMakeLists.txt;68;add_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;137;llama_test_cmd;/home/wayne/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-sampling]=] "/home/wayne/ubuntu-console/bin/test-sampling")
set_tests_properties([=[test-sampling]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/wayne/llama.cpp/tests/CMakeLists.txt;110;add_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;151;llama_build_and_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-reasoning-budget]=] "/home/wayne/ubuntu-console/bin/test-reasoning-budget")
set_tests_properties([=[test-reasoning-budget]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/wayne/llama.cpp/tests/CMakeLists.txt;110;add_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;152;llama_build_and_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-grammar-parser]=] "/home/wayne/ubuntu-console/bin/test-grammar-parser")
set_tests_properties([=[test-grammar-parser]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/wayne/llama.cpp/tests/CMakeLists.txt;110;add_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;153;llama_build_and_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-grammar-integration]=] "/home/wayne/ubuntu-console/bin/test-grammar-integration")
set_tests_properties([=[test-grammar-integration]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/wayne/llama.cpp/tests/CMakeLists.txt;110;add_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;154;llama_build_and_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-llama-grammar]=] "/home/wayne/ubuntu-console/bin/test-llama-grammar")
set_tests_properties([=[test-llama-grammar]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/wayne/llama.cpp/tests/CMakeLists.txt;110;add_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;155;llama_build_and_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-chat]=] "/home/wayne/ubuntu-console/bin/test-chat")
set_tests_properties([=[test-chat]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "/home/wayne/llama.cpp" _BACKTRACE_TRIPLES "/home/wayne/llama.cpp/tests/CMakeLists.txt;110;add_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;156;llama_build_and_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-json-schema-to-grammar]=] "/home/wayne/ubuntu-console/bin/test-json-schema-to-grammar")
set_tests_properties([=[test-json-schema-to-grammar]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "/home/wayne/llama.cpp" _BACKTRACE_TRIPLES "/home/wayne/llama.cpp/tests/CMakeLists.txt;110;add_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;159;llama_build_and_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-tokenizer-1-llama-spm]=] "/home/wayne/ubuntu-console/bin/test-tokenizer-1-spm" "/home/wayne/llama.cpp/models/ggml-vocab-llama-spm.gguf")
set_tests_properties([=[test-tokenizer-1-llama-spm]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/wayne/llama.cpp/tests/CMakeLists.txt;40;add_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;185;llama_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-llama-archs]=] "/home/wayne/ubuntu-console/bin/test-llama-archs")
set_tests_properties([=[test-llama-archs]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/wayne/llama.cpp/tests/CMakeLists.txt;110;add_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;190;llama_build_and_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-chat-peg-parser]=] "/home/wayne/ubuntu-console/bin/test-chat-peg-parser")
set_tests_properties([=[test-chat-peg-parser]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/wayne/llama.cpp/tests/CMakeLists.txt;110;add_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;193;llama_build_and_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-jinja]=] "/home/wayne/ubuntu-console/bin/test-jinja")
set_tests_properties([=[test-jinja]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/wayne/llama.cpp/tests/CMakeLists.txt;110;add_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;194;llama_build_and_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-jinja-py]=] "/home/wayne/ubuntu-console/bin/test-jinja" "-py")
set_tests_properties([=[test-jinja-py]=] PROPERTIES  LABELS "python" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/wayne/llama.cpp/tests/CMakeLists.txt;40;add_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;195;llama_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-chat-auto-parser]=] "/home/wayne/ubuntu-console/bin/test-chat-auto-parser")
set_tests_properties([=[test-chat-auto-parser]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "/home/wayne/llama.cpp" _BACKTRACE_TRIPLES "/home/wayne/llama.cpp/tests/CMakeLists.txt;110;add_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;196;llama_build_and_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-chat-template]=] "/home/wayne/ubuntu-console/bin/test-chat-template")
set_tests_properties([=[test-chat-template]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/wayne/llama.cpp/tests/CMakeLists.txt;110;add_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;197;llama_build_and_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-json-partial]=] "/home/wayne/ubuntu-console/bin/test-json-partial")
set_tests_properties([=[test-json-partial]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/wayne/llama.cpp/tests/CMakeLists.txt;110;add_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;198;llama_build_and_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-log]=] "/home/wayne/ubuntu-console/bin/test-log")
set_tests_properties([=[test-log]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/wayne/llama.cpp/tests/CMakeLists.txt;110;add_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;199;llama_build_and_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-peg-parser]=] "/home/wayne/ubuntu-console/bin/test-peg-parser")
set_tests_properties([=[test-peg-parser]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/wayne/llama.cpp/tests/CMakeLists.txt;110;add_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;200;llama_build_and_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-regex-partial]=] "/home/wayne/ubuntu-console/bin/test-regex-partial")
set_tests_properties([=[test-regex-partial]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/wayne/llama.cpp/tests/CMakeLists.txt;110;add_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;211;llama_build_and_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-download-model]=] "/usr/bin/cmake" "-DDEST=/home/wayne/ubuntu-console/tinyllamas/stories15M-q4_0.gguf" "-DNAME=tinyllamas/stories15M-q4_0.gguf" "-DHASH=SHA256=66967fbece6dbe97886593fdbb73589584927e29119ec31f08090732d1861739" "-P" "/home/wayne/llama.cpp/cmake/download-models.cmake")
set_tests_properties([=[test-download-model]=] PROPERTIES  FIXTURES_SETUP "test-download-model" _BACKTRACE_TRIPLES "/home/wayne/llama.cpp/tests/CMakeLists.txt;222;add_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-thread-safety]=] "/home/wayne/ubuntu-console/bin/test-thread-safety" "-m" "/home/wayne/ubuntu-console/tinyllamas/stories15M-q4_0.gguf" "-ngl" "99" "-p" "The meaning of life is" "-n" "128" "-c" "256" "-ub" "32" "-np" "4" "-t" "2")
set_tests_properties([=[test-thread-safety]=] PROPERTIES  FIXTURES_REQUIRED "test-download-model" LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/wayne/llama.cpp/tests/CMakeLists.txt;110;add_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;230;llama_build_and_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-arg-parser]=] "/home/wayne/ubuntu-console/bin/test-arg-parser")
set_tests_properties([=[test-arg-parser]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/wayne/llama.cpp/tests/CMakeLists.txt;110;add_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;233;llama_build_and_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-opt]=] "/home/wayne/ubuntu-console/bin/test-opt")
set_tests_properties([=[test-opt]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/wayne/llama.cpp/tests/CMakeLists.txt;110;add_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;237;llama_build_and_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-gguf]=] "/home/wayne/ubuntu-console/bin/test-gguf")
set_tests_properties([=[test-gguf]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/wayne/llama.cpp/tests/CMakeLists.txt;110;add_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;239;llama_build_and_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-backend-ops]=] "/home/wayne/ubuntu-console/bin/test-backend-ops")
set_tests_properties([=[test-backend-ops]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/wayne/llama.cpp/tests/CMakeLists.txt;110;add_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;240;llama_build_and_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-model-load-cancel]=] "/home/wayne/ubuntu-console/bin/test-model-load-cancel")
set_tests_properties([=[test-model-load-cancel]=] PROPERTIES  LABELS "model" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/wayne/llama.cpp/tests/CMakeLists.txt;110;add_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;242;llama_build_and_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-autorelease]=] "/home/wayne/ubuntu-console/bin/test-autorelease")
set_tests_properties([=[test-autorelease]=] PROPERTIES  LABELS "model" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/wayne/llama.cpp/tests/CMakeLists.txt;110;add_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;243;llama_build_and_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-backend-sampler]=] "/home/wayne/ubuntu-console/bin/test-backend-sampler")
set_tests_properties([=[test-backend-sampler]=] PROPERTIES  LABELS "model" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/wayne/llama.cpp/tests/CMakeLists.txt;110;add_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;244;llama_build_and_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-state-restore-fragmented]=] "/home/wayne/ubuntu-console/bin/test-state-restore-fragmented" "-m" "/home/wayne/ubuntu-console/tinyllamas/stories15M-q4_0.gguf")
set_tests_properties([=[test-state-restore-fragmented]=] PROPERTIES  FIXTURES_REQUIRED "test-download-model" LABELS "model" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/wayne/llama.cpp/tests/CMakeLists.txt;110;add_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;248;llama_build_and_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-barrier]=] "/home/wayne/ubuntu-console/bin/test-barrier")
set_tests_properties([=[test-barrier]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/wayne/llama.cpp/tests/CMakeLists.txt;110;add_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;253;llama_build_and_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-quantize-fns]=] "/home/wayne/ubuntu-console/bin/test-quantize-fns")
set_tests_properties([=[test-quantize-fns]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/wayne/llama.cpp/tests/CMakeLists.txt;110;add_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;254;llama_build_and_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-quantize-perf]=] "/home/wayne/ubuntu-console/bin/test-quantize-perf")
set_tests_properties([=[test-quantize-perf]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/wayne/llama.cpp/tests/CMakeLists.txt;110;add_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;255;llama_build_and_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-rope]=] "/home/wayne/ubuntu-console/bin/test-rope")
set_tests_properties([=[test-rope]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/wayne/llama.cpp/tests/CMakeLists.txt;110;add_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;256;llama_build_and_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-mtmd-c-api]=] "/home/wayne/ubuntu-console/bin/test-mtmd-c-api")
set_tests_properties([=[test-mtmd-c-api]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/wayne/llama.cpp/tests/CMakeLists.txt;110;add_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;261;llama_build_and_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-gguf-model-data]=] "/home/wayne/ubuntu-console/bin/test-gguf-model-data")
set_tests_properties([=[test-gguf-model-data]=] PROPERTIES  LABELS "model" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/wayne/llama.cpp/tests/CMakeLists.txt;40;add_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;275;llama_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-alloc]=] "/home/wayne/ubuntu-console/bin/test-alloc")
set_tests_properties([=[test-alloc]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/home/wayne/llama.cpp/tests/CMakeLists.txt;110;add_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;284;llama_build_and_test;/home/wayne/llama.cpp/tests/CMakeLists.txt;0;")
