"""Call-flow HTML / Mermaid export for kgraph.

Generates a Mermaid flowchart and an HTML page for interactive navigation
of call graphs extracted from AST sources.

Accepts ``Graph`` models or legacy dicts.
"""

from __future__ import annotations

import re

from .models import Graph


def generate_call_flow_mermaid(graph: Graph | dict, **kwargs) -> str:
    """Generate a Mermaid flowchart from AST-extracted call graph.

    Filters to nodes with 'function', 'class', 'module' types plus
    their call edges.
    """
    if isinstance(graph, dict):
        graph = Graph.from_dict(graph)

    title = kwargs.get("title", "Call Flow")

    relevant_types = {"function", "class", "module", "call", "variable"}
    relevant_nodes: dict[str, dict] = {}
    for n in graph.nodes:
        if n.type.lower() in relevant_types or n.source == "ast":
            relevant_nodes[n.id] = n.model_dump(mode="json", exclude_none=True)

    relevant_edges: list[tuple[str, str, str]] = []
    for e in graph.edges:
        if e.source in relevant_nodes and e.target in relevant_nodes:
            if e.label in ("defines", "calls", "imports", "resolves_to"):
                relevant_edges.append((e.source, e.target, e.label))

    if not relevant_nodes:
        return "```mermaid\nflowchart LR\n  NoAST[No AST data available]\n```"

    lines = ["```mermaid", "flowchart LR", f"  %% {title} — generated by kgraph", ""]

    def safe_name(nid: str) -> tuple[str, str]:
        node = relevant_nodes.get(nid, {})
        label = str(node.get("label", nid))
        safe_id = re.sub(r"[^a-zA-Z0-9_]+", "_", nid)
        if safe_id[0].isdigit():
            safe_id = "n" + safe_id
        return safe_id, label

    for nid in relevant_nodes:
        safe, label = safe_name(nid)
        ntype = str(relevant_nodes[nid].get("type", "")).lower()
        if ntype == "module":
            shape = f'(["{label}"])'
        elif ntype == "class":
            shape = f'["{label}"]'
        elif ntype in ("function", "call"):
            shape = f'("{label}")'
        else:
            shape = f'["{label}"]'
        lines.append(f"  {safe}{shape}")

    edge_styles = {
        "calls": " -->|calls| ",
        "defines": " -.->|defines| ",
        "imports": " ==>|imports| ",
        "resolves_to": " -.->|resolves_to| ",
    }
    for src, dst, label in relevant_edges:
        src_safe, _ = safe_name(src)
        dst_safe, _ = safe_name(dst)
        style = edge_styles.get(label, " --- ")
        lines.append(f"  {src_safe}{style}{dst_safe}")

    lines.append("```")
    return "\n".join(lines)


def generate_call_flow_html(graph: Graph | dict, **kwargs) -> str:
    """Generate a full HTML page with embedded Mermaid call flow."""
    if isinstance(graph, dict):
        graph = Graph.from_dict(graph)

    title = kwargs.get("title", "Call Flow — kgraph")
    mermaid_code = generate_call_flow_mermaid(graph, title=title)

    ast_nodes = [
        n for n in graph.nodes
        if n.source == "ast" or n.type.lower() in ("function", "class", "module", "call")
    ]

    html = f"""<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{title}</title>
    <script src="https://cdn.jsdelivr.net/npm/mermaid@9/dist/mermaid.min.js"></script>
    <style>
      body {{ font-family: system-ui, sans-serif; margin: 24px; background: #f8fafc; color: #1e293b; }}
      h1 {{ font-size: 22px; margin-bottom: 4px; }}
      .subtitle {{ color: #64748b; font-size: 13px; margin-bottom: 20px; }}
      .mermaid {{ background: #fff; padding: 20px; border-radius: 10px; box-shadow: 0 1px 4px rgba(0,0,0,0.08); }}
      table {{ border-collapse: collapse; width: 100%; margin-top: 24px; font-size: 13px; }}
      th, td {{ text-align: left; padding: 8px 10px; border-bottom: 1px solid #e2e8f0; }}
      th {{ background: #f1f5f9; font-weight: 600; }}
      .confidence {{ display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 11px; font-weight: 600; }}
      .EXTRACTED {{ background: #d1fae5; color: #065f46; }}
      .INFERRED {{ background: #fef3c7; color: #92400e; }}
      .AMBIGUOUS {{ background: #fee2e2; color: #991b1b; }}
    </style>
  </head>
  <body>
    <h1>{title}</h1>
    <p class="subtitle">Generated by kgraph — {len(ast_nodes)} AST nodes</p>
    <div class="mermaid">
{mermaid_code}
    </div>
    <h2 style="margin-top:28px;font-size:16px;">AST Nodes</h2>
    <table>
      <tr><th>ID</th><th>Label</th><th>Type</th><th>Language</th><th>File</th><th>Confidence</th></tr>
"""

    for n in ast_nodes:
        conf = n.confidence or "INFERRED"
        html += f"""      <tr>
        <td><code>{n.id}</code></td>
        <td>{n.label}</td>
        <td>{n.type}</td>
        <td>{n.language}</td>
        <td>{n.file}</td>
        <td><span class="confidence {conf}">{conf}</span></td>
      </tr>
"""

    html += """    </table>
    <script>mermaid.initialize({ startOnLoad: true, theme: 'default', flowchart: { useMaxWidth: true } });</script>
  </body>
</html>"""

    return html