"""Call-flow HTML / Mermaid export for kgraph.

Generates a Mermaid flowchart and an HTML page for interactive navigation
of call graphs extracted from AST sources.

Also produces a lightweight call-flow HTML view (HTML + embedded Mermaid).
"""

import re


def generate_call_flow_mermaid(graph: dict, **kwargs) -> str:
    """Generate a Mermaid flowchart from AST-extracted call graph.

    Filters to nodes with 'function', 'class', 'module' types plus
    their call edges.

    Args:
        graph: Graph dict.
        title: Optional diagram title.

    Returns:
        Mermaid markdown string.
    """
    title = kwargs.get('title', 'Call Flow')
    nodes = graph.get('nodes', []) or []
    edges = graph.get('edges', []) or []

    # Filter to AST-relevant nodes and edges
    relevant_types = {'function', 'class', 'module', 'call', 'variable'}
    relevant_nodes = {}
    for n in nodes:
        ntype = str(n.get('type', '')).lower()
        if ntype in relevant_types or n.get('source') == 'ast':
            nid = str(n.get('id', ''))
            if nid:
                relevant_nodes[nid] = n

    relevant_edges = []
    for e in edges:
        src = str(e.get('from', e.get('source', '')))
        dst = str(e.get('to', e.get('target', '')))
        if src in relevant_nodes and dst in relevant_nodes:
            label = str(e.get('label', ''))
            if label in ('defines', 'calls', 'imports', 'resolves_to'):
                relevant_edges.append((src, dst, label))

    if not relevant_nodes:
        return '```mermaid\nflowchart LR\n  NoAST[No AST data available]\n```'

    lines = []
    lines.append('```mermaid')
    lines.append('flowchart LR')
    lines.append(f'  %% {title} — generated by kgraph')
    lines.append('')

    def safe_name(nid: str) -> str:
        """Generate a safe Mermaid node id and label."""
        node = relevant_nodes.get(nid, {})
        label = str(node.get('label', nid))
        # Clean for Mermaid
        safe_id = re.sub(r'[^a-zA-Z0-9_]+', '_', nid)
        if safe_id[0].isdigit():
            safe_id = 'n' + safe_id
        return safe_id, label

    # Add nodes
    for nid in relevant_nodes:
        safe, label = safe_name(nid)
        ntype = str(relevant_nodes[nid].get('type', '')).lower()
        shape = ''
        if ntype == 'module':
            shape = '(["' + label + '"])'
        elif ntype == 'class':
            shape = '["' + label + '"]'
        elif ntype in ('function', 'call'):
            shape = '("' + label + '")'
        else:
            shape = '["' + label + '"]'
        lines.append(f'  {safe}{shape}')

    # Add edges
    for src, dst, label in relevant_edges:
        src_safe, _ = safe_name(src)
        dst_safe, _ = safe_name(dst)
        style = ''
        if label == 'calls':
            style = ' -->|calls| '
        elif label == 'defines':
            style = ' -.->|defines| '
        elif label == 'imports':
            style = ' ==>|imports| '
        elif label == 'resolves_to':
            style = ' -.->|resolves_to| '
        else:
            style = ' --- '
        lines.append(f'  {src_safe}{style}{dst_safe}')

    lines.append('```')
    return '\n'.join(lines)


def generate_call_flow_html(graph: dict, **kwargs) -> str:
    """Generate a full HTML page with embedded Mermaid call flow.

    Args:
        graph: Graph dict.
        title: Optional page title.
        outpath: Optional output file path.

    Returns:
        Full HTML string.
    """
    title = kwargs.get('title', 'Call Flow — kgraph')
    mermaid_code = generate_call_flow_mermaid(graph, title=title)

    # Also build a node-detail table
    nodes = graph.get('nodes', []) or []
    ast_nodes = [n for n in nodes if n.get('source') == 'ast' or str(n.get('type', '')).lower() in
                 ('function', 'class', 'module', 'call')]

    html = f'''<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{title}</title>
    <script src="https://cdn.jsdelivr.net/npm/mermaid@9/dist/mermaid.min.js"></script>
    <style>
      body {{ font-family: system-ui, sans-serif; margin: 24px; background: #f8fafc; color: #1e293b; }}
      h1 {{ font-size: 22px; margin-bottom: 4px; }}
      .subtitle {{ color: #64748b; font-size: 13px; margin-bottom: 20px; }}
      .mermaid {{ background: #fff; padding: 20px; border-radius: 10px; box-shadow: 0 1px 4px rgba(0,0,0,0.08); }}
      table {{ border-collapse: collapse; width: 100%; margin-top: 24px; font-size: 13px; }}
      th, td {{ text-align: left; padding: 8px 10px; border-bottom: 1px solid #e2e8f0; }}
      th {{ background: #f1f5f9; font-weight: 600; }}
      .confidence {{ display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 11px; font-weight: 600; }}
      .EXTRACTED {{ background: #d1fae5; color: #065f46; }}
      .INFERRED {{ background: #fef3c7; color: #92400e; }}
      .AMBIGUOUS {{ background: #fee2e2; color: #991b1b; }}
    </style>
  </head>
  <body>
    <h1>{title}</h1>
    <p class="subtitle">Generated by kgraph — {len(ast_nodes)} AST nodes</p>
    <div class="mermaid">
{mermaid_code}
    </div>
    <h2 style="margin-top:28px;font-size:16px;">AST Nodes</h2>
    <table>
      <tr>
        <th>ID</th>
        <th>Label</th>
        <th>Type</th>
        <th>Language</th>
        <th>File</th>
        <th>Confidence</th>
      </tr>
'''

    for n in ast_nodes:
        nid = str(n.get('id', ''))
        label = str(n.get('label', ''))
        ntype = str(n.get('type', ''))
        lang = str(n.get('language', ''))
        file = str(n.get('file', ''))
        conf = str(n.get('confidence', 'INFERRED'))
        html += f'''      <tr>
        <td><code>{nid}</code></td>
        <td>{label}</td>
        <td>{ntype}</td>
        <td>{lang}</td>
        <td>{file}</td>
        <td><span class="confidence {conf}">{conf}</span></td>
      </tr>
'''

    html += '''    </table>
    <script>mermaid.initialize({ startOnLoad: true, theme: 'default', flowchart: { useMaxWidth: true } });</script>
  </body>
</html>'''

    return html
