"""GRAPH_REPORT.md generator — surprising connections, god nodes, and graph insights.

Analyzes a kgraph graph and produces a structured markdown report with:
- God nodes (most central concepts)
- Community structure
- Surprising/unexpected connections
- Edge type statistics
- Token-reduction estimates vs raw files

Accepts ``Graph`` models or legacy dicts.
"""

from __future__ import annotations

import os

from .community import compute_centrality, detect_communities, find_god_nodes
from .models import Graph


def generate_report(graph: Graph | dict, **kwargs) -> str:
    """Generate a GRAPH_REPORT.md string from a kgraph graph.

    Args:
        graph: Graph model or dict.
        title: Optional report title (default: 'Knowledge Graph Report').
        outpath: If set, write report to this file.

    Returns:
        Markdown report text.
    """
    if isinstance(graph, dict):
        graph = Graph.from_dict(graph)

    title = kwargs.get("title", "Knowledge Graph Report")
    outpath = kwargs.get("outpath")

    nodes = graph.nodes
    edges = graph.edges

    # ── Basic stats ──
    node_types: dict[str, int] = {}
    edge_labels: dict[str, int] = {}
    file_count = 0
    concept_count = 0
    for n in nodes:
        ntype = n.type.lower()
        node_types[ntype] = node_types.get(ntype, 0) + 1
        if ntype == "file":
            file_count += 1
        elif ntype not in ("file", "chunk", "summary"):
            concept_count += 1

    for e in edges:
        lbl = e.label.strip() or "related"
        edge_labels[lbl] = edge_labels.get(lbl, 0) + 1

    # ── Centrality / god nodes ──
    god_nodes = find_god_nodes(graph, top_n=15)
    centralities = compute_centrality(graph)

    # ── Communities ──
    community_graph = detect_communities(graph)
    communities = community_graph.meta.communities

    # ── Surprising connections ──
    surprising = _find_surprising_connections(graph, centralities, god_nodes)

    # ── Token-reduction estimate ──
    token_estimate = _estimate_token_savings(graph)

    # ── Build report ──
    lines: list[str] = []
    lines.append(f"# {title}")
    lines.append("")
    lines.append("_Generated by kgraph_")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- **Nodes:** {len(nodes)}")
    lines.append(f"- **Edges:** {len(edges)}")
    lines.append(f"- **Files:** {file_count}")
    lines.append(f"- **Concepts (non-file):** {concept_count}")
    lines.append(f"- **Node types:** {len(node_types)} types")
    lines.append(f"- **Communities detected:** {len(communities)}")
    lines.append("")

    # ── God nodes ──
    lines.append("## God Nodes (Most Central)")
    lines.append("")
    lines.append("| Rank | Node | Composite | Degree | Betweenness | Eigenvector |")
    lines.append("|------|------|-----------|--------|-------------|-------------|")
    for idx, gn in enumerate(god_nodes[:10], 1):
        lines.append(
            f'| {idx} | {gn["label"]} | {gn["composite_score"]:.3f} | '
            f'{gn["degree"]} | {gn["betweenness"]:.4f} | {gn["eigenvector"]:.4f} |'
        )
    lines.append("")

    # ── Communities ──
    if communities:
        lines.append("## Community Structure")
        lines.append("")
        for c in communities:
            lines.append(f'- **{c["label"]}** — {c["size"]} members')
        lines.append("")

    # ── Surprising connections ──
    if surprising:
        lines.append("## Surprising / Unexpected Connections")
        lines.append("")
        lines.append("These edges bridge disparate concepts or have unusually high centrality for their degree:")
        lines.append("")
        for s in surprising[:8]:
            lines.append(f'- **{s["src_label"]}** → **{s["dst_label"]}** ({s["label"]})')
            if s.get("reason"):
                lines.append(f'  - {s["reason"]}')
        lines.append("")

    # ── Edge type distribution ──
    lines.append("## Edge Type Distribution")
    lines.append("")
    sorted_labels = sorted(edge_labels.items(), key=lambda x: -x[1])
    for lbl, count in sorted_labels[:20]:
        bar = "█" * min(count, 40)
        lines.append(f"- {lbl}: {count} {bar}")
    if len(sorted_labels) > 20:
        lines.append(f"- *... and {len(sorted_labels) - 20} more edge types*")
    lines.append("")

    # ── Type counts ──
    lines.append("## Node Type Distribution")
    lines.append("")
    sorted_types = sorted(node_types.items(), key=lambda x: -x[1])
    for ntype, count in sorted_types:
        lines.append(f"- **{ntype}:** {count}")
    lines.append("")

    # ── Token savings ──
    if token_estimate:
        lines.append("## Token-Reduction Estimate")
        lines.append("")
        lines.append(f'- Raw tokens (if every node/edge were a separate item): ~{token_estimate["raw_tokens"]}')
        lines.append(f'- Graph-compressed tokens (using graph structure): ~{token_estimate["compressed_tokens"]}')
        lines.append(f'- **Estimated savings: ~{token_estimate["savings_pct"]}%**')
        lines.append(f'- Equivalent to ~{token_estimate["compressed_tokens"]} tokens for contextual retrieval')
        lines.append("")

    # ── Export ──
    if outpath:
        os.makedirs(os.path.dirname(os.path.abspath(outpath)), exist_ok=True)
        with open(outpath, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))
        print(f"Wrote {outpath}")

    return "\n".join(lines)


def _find_surprising_connections(graph: Graph, centralities: dict, god_nodes: list) -> list:
    """Find edges that bridge otherwise disconnected communities."""
    god_ids = {gn["id"] for gn in god_nodes}

    if not centralities:
        return []

    result = []
    for e in graph.edges:
        src_c = centralities.get(e.source, {})
        dst_c = centralities.get(e.target, {})
        src_btw = src_c.get("betweenness", 0)
        dst_btw = dst_c.get("betweenness", 0)
        src_eig = src_c.get("eigenvector", 0)
        dst_eig = dst_c.get("eigenvector", 0)

        if src_btw > 0.05 and dst_btw > 0.05 and src_eig < 0.1 and dst_eig < 0.1:
            reason = (
                f"Both endpoints have high betweenness ({src_btw:.3f}, {dst_btw:.3f}) "
                f"but low eigenvector — this edge likely connects different communities."
            )
            result.append({
                "src": e.source,
                "src_label": str(src_c.get("label", e.source)),
                "dst": e.target,
                "dst_label": str(dst_c.get("label", e.target)),
                "label": e.label,
                "reason": reason,
                "score": (src_btw + dst_btw) * 2 - (src_eig + dst_eig),
            })
        elif e.source in god_ids and e.target not in god_ids and src_eig > 0.05:
            reason = (
                f'{src_c.get("label", e.source)} is a god node connecting to '
                f'lower-centrality {dst_c.get("label", e.target)}.'
            )
            result.append({
                "src": e.source,
                "src_label": str(src_c.get("label", e.source)),
                "dst": e.target,
                "dst_label": str(dst_c.get("label", e.target)),
                "label": e.label,
                "reason": reason,
                "score": src_btw + dst_btw,
            })

    result.sort(key=lambda x: -x["score"])
    return result


def _estimate_token_savings(graph: Graph) -> dict:
    """Rough estimate of token reduction from graph vs raw context."""
    nodes = graph.nodes
    edges = graph.edges

    raw_tokens = len(nodes) * 30 + len(edges) * 20

    unique_labels = {n.label for n in nodes if n.label}
    unique_types = {n.type for n in nodes if n.type}

    compressed_tokens = len(unique_types) * 50 + len(unique_labels) * 5 + len(edges) * 8 + len(nodes) * 3

    if raw_tokens <= 0:
        return {}

    savings_pct = round((1 - compressed_tokens / raw_tokens) * 100, 1)
    return {
        "raw_tokens": raw_tokens,
        "compressed_tokens": compressed_tokens,
        "savings_pct": savings_pct,
    }