"""GRAPH_REPORT.md generator — surprising connections, god nodes, and graph insights.

Analyzes a kgraph graph dict and produces a structured markdown report
with:
- God nodes (most central concepts)
- Community structure
- Surprising/unexpected connections
- Edge type statistics
- Token-reduction estimates vs raw files
"""

import os
import json
from .community import compute_centrality, find_god_nodes, detect_communities
from .constants import normalize_canonical_name


def generate_report(graph: dict, **kwargs) -> str:
    """Generate a GRAPH_REPORT.md string from a kgraph graph dict.

    Args:
        graph: The graph dict with 'nodes' and 'edges'.
        title: Optional report title (default: 'Knowledge Graph Report').
        outpath: If set, write report to this file.

    Returns:
        Markdown report text.
    """
    title = kwargs.get('title', 'Knowledge Graph Report')
    outpath = kwargs.get('outpath', None)

    nodes = graph.get('nodes', []) or []
    edges = graph.get('edges', []) or []

    # ── Basic stats ──
    node_types = {}
    edge_labels = {}
    file_count = 0
    concept_count = 0
    for n in nodes:
        ntype = str(n.get('type', 'unknown')).lower()
        node_types[ntype] = node_types.get(ntype, 0) + 1
        if ntype == 'file':
            file_count += 1
        elif ntype not in ('file', 'chunk', 'summary'):
            concept_count += 1

    for e in edges:
        lbl = str(e.get('label', 'related')).strip() or 'related'
        edge_labels[lbl] = edge_labels.get(lbl, 0) + 1

    # ── Centrality / god nodes ──
    god_nodes = find_god_nodes(graph, top_n=15)
    centralities = compute_centrality(graph)

    # ── Communities ──
    community_graph = detect_communities(graph)
    communities = (community_graph.get('_meta') or {}).get('communities', [])

    # ── Surprising connections ──
    # Edges with high betweenness but low degree = bridging connectors
    surprising = _find_surprising_connections(graph, centralities, god_nodes)

    # ── Token-reduction estimate ──
    token_estimate = _estimate_token_savings(graph)

    # ── Build report ──
    lines = []
    lines.append(f'# {title}')
    lines.append('')
    lines.append(f'_Generated by kgraph_')
    lines.append('')
    lines.append('## Summary')
    lines.append('')
    lines.append(f'- **Nodes:** {len(nodes)}')
    lines.append(f'- **Edges:** {len(edges)}')
    lines.append(f'- **Files:** {file_count}')
    lines.append(f'- **Concepts (non-file):** {concept_count}')
    lines.append(f'- **Node types:** {len(node_types)} types')
    lines.append(f'- **Communities detected:** {len(communities)}')
    lines.append('')

    # ── God nodes ──
    lines.append('## God Nodes (Most Central)')
    lines.append('')
    lines.append('| Rank | Node | Composite | Degree | Betweenness | Eigenvector |')
    lines.append('|------|------|-----------|--------|-------------|-------------|')
    for idx, gn in enumerate(god_nodes[:10], 1):
        lines.append(
            f'| {idx} | {gn["label"]} | {gn["composite_score"]:.3f} | '
            f'{gn["degree"]} | {gn["betweenness"]:.4f} | {gn["eigenvector"]:.4f} |'
        )
    lines.append('')

    # ── Communities ──
    if communities:
        lines.append('## Community Structure')
        lines.append('')
        for c in communities:
            lines.append(f'- **{c["label"]}** — {c["size"]} members')
        lines.append('')

    # ── Surprising connections ──
    if surprising:
        lines.append('## Surprising / Unexpected Connections')
        lines.append('')
        lines.append('These edges bridge disparate concepts or have unusually high centrality for their degree:')
        lines.append('')
        for s in surprising[:8]:
            lines.append(f'- **{s["src_label"]}** → **{s["dst_label"]}** ({s["label"]})')
            if s.get('reason'):
                lines.append(f'  - {s["reason"]}')
        lines.append('')

    # ── Edge type distribution ──
    lines.append('## Edge Type Distribution')
    lines.append('')
    sorted_labels = sorted(edge_labels.items(), key=lambda x: -x[1])
    for lbl, count in sorted_labels[:20]:
        bar = '█' * min(count, 40)
        lines.append(f'- {lbl}: {count} {bar}')
    if len(sorted_labels) > 20:
        lines.append(f'- *... and {len(sorted_labels) - 20} more edge types*')
    lines.append('')

    # ── Type counts ──
    lines.append('## Node Type Distribution')
    lines.append('')
    sorted_types = sorted(node_types.items(), key=lambda x: -x[1])
    for ntype, count in sorted_types:
        lines.append(f'- **{ntype}:** {count}')
    lines.append('')

    # ── Token savings ──
    if token_estimate:
        lines.append('## Token-Reduction Estimate')
        lines.append('')
        lines.append(f'- Raw tokens (if every node/edge were a separate item): ~{token_estimate["raw_tokens"]}')
        lines.append(f'- Graph-compressed tokens (using graph structure): ~{token_estimate["compressed_tokens"]}')
        lines.append(f'- **Estimated savings: ~{token_estimate["savings_pct"]}%**')
        lines.append(f'- Equivalent to ~{token_estimate["compressed_tokens"]} tokens for contextual retrieval')
        lines.append('')

    # ── Export ──
    if outpath:
        os.makedirs(os.path.dirname(os.path.abspath(outpath)), exist_ok=True)
        with open(outpath, 'w', encoding='utf-8') as f:
            f.write('\n'.join(lines))
        print(f'Wrote {outpath}')

    return '\n'.join(lines)


def _find_surprising_connections(graph: dict, centralities: dict, god_nodes: list) -> list:
    """Find edges that bridge otherwise disconnected communities."""
    nodes = graph.get('nodes', [])
    edges = graph.get('edges', [])

    node_ids = {str(n.get('id', '')): n for n in nodes}
    god_ids = {gn['id'] for gn in god_nodes}

    # Build co-community map from centralities
    if not centralities:
        return []

    # Score edges by surprisingness:
    # high betweenness bridge + low eigenvector on both ends = unusual link
    result = []
    for e in edges:
        src = str(e.get('from', e.get('source', '')))
        dst = str(e.get('to', e.get('target', '')))
        if not src or not dst:
            continue
        src_c = centralities.get(src, {})
        dst_c = centralities.get(dst, {})
        src_btw = src_c.get('betweenness', 0)
        dst_btw = dst_c.get('betweenness', 0)
        src_eig = src_c.get('eigenvector', 0)
        dst_eig = dst_c.get('eigenvector', 0)

        # High betweenness bridge
        if src_btw > 0.05 and dst_btw > 0.05 and src_eig < 0.1 and dst_eig < 0.1:
            reason = f'Both endpoints have high betweenness ({src_btw:.3f}, {dst_btw:.3f}) but low eigenvector — this edge likely connects different communities.'
            result.append({
                'src': src,
                'src_label': str(src_c.get('label', src)),
                'dst': dst,
                'dst_label': str(dst_c.get('label', dst)),
                'label': str(e.get('label', 'related')),
                'reason': reason,
                'score': (src_btw + dst_btw) * 2 - (src_eig + dst_eig),
            })
        elif src in god_ids and dst not in god_ids and src_eig > 0.05:
            reason = f'{src_c.get("label", src)} is a god node connecting to lower-centrality {dst_c.get("label", dst)}.'
            result.append({
                'src': src,
                'src_label': str(src_c.get('label', src)),
                'dst': dst,
                'dst_label': str(dst_c.get('label', dst)),
                'label': str(e.get('label', 'related')),
                'reason': reason,
                'score': src_btw + dst_btw,
            })

    result.sort(key=lambda x: -x['score'])
    return result


def _estimate_token_savings(graph: dict) -> dict:
    """Rough estimate of token reduction from graph vs raw context."""
    nodes = graph.get('nodes', []) or []
    edges = graph.get('edges', []) or []

    # Rough tokens: each node ~30 tokens, each edge ~20 tokens
    raw_tokens = len(nodes) * 30 + len(edges) * 20

    # Graph compression: assume the graph structure tokens + labels is smaller
    unique_labels = set()
    for n in nodes:
        lbl = str(n.get('label', '') or '')
        if lbl:
            unique_labels.add(lbl)
    unique_types = set()
    for n in nodes:
        ntype = str(n.get('type', '') or '')
        if ntype:
            unique_types.add(ntype)

    # Compressed: node type definitions (~50 each) + label references (~5 each) + edge structures (~8 each)
    compressed_tokens = len(unique_types) * 50 + len(unique_labels) * 5 + len(edges) * 8 + len(nodes) * 3

    if raw_tokens <= 0:
        return {}

    savings_pct = round((1 - compressed_tokens / raw_tokens) * 100, 1)
    return {
        'raw_tokens': raw_tokens,
        'compressed_tokens': compressed_tokens,
        'savings_pct': savings_pct,
    }
